/**
 * Writes the service worker after `next build`, listing every file in `out/`.
 *
 * Each tool is its own page and its own code chunk. Caching only what a visit
 * happens to load would leave most tools missing offline, so every file in the
 * build is cached on install — which is what makes "Offline ready" true for all
 * of them. Pages are stored under their clean URLs (/tools/qr-code/).
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const OUT = 'out';
const walk = (dir) => readdirSync(dir).flatMap((name) => {
  const path = join(dir, name);
  return statSync(path).isDirectory() ? walk(path) : [path];
});

const files = walk(OUT)
  .map((path) => '/' + relative(OUT, path).split(sep).join('/'))
  .filter((url) => url !== '/sw.js' && !url.endsWith('.map') && !url.endsWith('.txt'))
  .sort();

const hash = createHash('sha256');
for (const url of files) hash.update(url).update(readFileSync(join(OUT, url)));
const version = hash.digest('hex').slice(0, 12);
// "/tools/qr-code/index.html" is requested as "/tools/qr-code/".
const precache = files.map((url) => url.replace(/index\.html$/, ''));

const worker = `/* Generated by scripts/build-sw.mjs — do not edit. */
const VERSION = ${JSON.stringify(version)};
const CACHE = 'pocket-tools-' + VERSION;
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => Promise.all(PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' })).catch(() => undefined))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith('pocket-tools-') && key !== CACHE).map((key) => caches.delete(key)));
    await self.clients.claim();
    for (const client of await self.clients.matchAll()) client.postMessage('precached');
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    // The page from cache at once, refreshed in the background for next time.
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const path = url.pathname.endsWith('/') ? url.pathname : url.pathname + '/';
      const cached = (await cache.match(path)) || (await cache.match(url.pathname));
      const network = fetch(request).then((response) => {
        if (response.ok) cache.put(path, response.clone());
        return response;
      }).catch(() => undefined);
      return cached || (await network) || (await cache.match('/404.html')) || (await cache.match('/')) || new Response('Offline', { status: 503 });
    })());
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => hit || fetch(request).then((response) => {
      if (response.ok) caches.open(CACHE).then((cache) => cache.put(request, response.clone()));
      return response;
    })),
  );
});
`;

writeFileSync(join(OUT, 'sw.js'), worker);
console.log(`sw.js  ${precache.length} files precached, version ${version}`);
