/**
 * Writes the service worker after `next build`, listing every file in `out/`.
 *
 * Next names its chunks by content hash, so a hand-written precache list rots on
 * the next build. And caching only what a page happens to fetch leaves the
 * tools you have not opened yet unavailable offline — each one is its own
 * lazily loaded chunk. Listing the whole build is what makes "Offline ready"
 * true for all six tools, not just the first one you looked at.
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const OUT = 'out';

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const files = walk(OUT)
  .map((path) => '/' + relative(OUT, path).split(sep).join('/'))
  .filter((url) => url !== '/sw.js' && !url.endsWith('.map') && !url.endsWith('.txt'))
  .sort();

const hash = createHash('sha256');
for (const url of files) hash.update(url).update(readFileSync(join(OUT, url)));
const version = hash.digest('hex').slice(0, 12);
const precache = ['/', ...files.filter((url) => url !== '/index.html'), '/index.html'];

const worker = `/* Generated by scripts/build-sw.mjs — do not edit. */
const VERSION = ${JSON.stringify(version)};
const CACHE = 'playground-' + VERSION;
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // One file failing must not leave the whole app uncached.
      Promise.all(PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' })).catch(() => undefined))),
    ).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith('playground-') && key !== CACHE).map((key) => caches.delete(key)));
    await self.clients.claim();
    for (const client of await self.clients.matchAll()) client.postMessage('precached');
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Pages: answer from cache at once, refresh in the background. Instant on a
  // train, current on the next visit.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = (await cache.match('/')) || (await cache.match('/index.html'));
      const network = fetch(request).then((response) => {
        if (response.ok) cache.put('/', response.clone());
        return response;
      }).catch(() => undefined);
      return cached || (await network) || new Response('Offline', { status: 503 });
    })());
    return;
  }

  // Everything else is content-hashed or versioned: cache first.
  event.respondWith(
    caches.match(request).then((hit) => hit || fetch(request).then((response) => {
      if (response.ok) caches.open(CACHE).then((cache) => cache.put(request, response.clone()));
      return response;
    })),
  );
});
`;

writeFileSync(join(OUT, 'sw.js'), worker);
console.log(`sw.js  ${precache.length} files precached, version ${version}`);
